plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/rguktrkvalley/aadhya3.0/scamshield-india/build"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/rguktrkvalley/aadhya3.0/scamshield-india"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]